#!/usr/bin/env bash
#comen
echo $$>/var/run/myscript.pid
trap 'echo "Y U no love me?!"' INT
trap 'echo "I hate the kill command";rm -f /var/run/myscript.pid;exit' TERM
trap 'rm -f /var/run/myscript.pid;exit' QUIT
while :;do echo "To infinity and beyond";sleep 1;done
